### ISSUE TITLE
Changing the game in the Update Scores section does not change the stats

### ISSUE THREAD

**Issue by stegreen1980** [lucacri/nycgha-stats#3]
When choosing a different game in the game drop-down, the stats do not change.  See images.
![image](https://cloud.githubusercontent.com/assets/11998123/7208006/9b47eb50-e50b-11e4-96c3-f1499d9e9410.png)
![image](https://cloud.githubusercontent.com/assets/11998123/7208016/a846a666-e50b-11e4-949e-12ae4913a834.png)

**Comment by lucacri** [comment]
I'm on a plane but.. Are you sure you have JavaScript enabled?

**Comment by stegreen1980** [comment]
It appears to work on my home computer.  I think it has something to do with my work network.  I tried accessing http://nycgha.lucacri.dyndns-server.com/index.php at work and I got an error saying that the website violates AIG policy.  Not a big deal.  This issue seems to be resolved.
