### ISSUE TITLE
New Season does not appear for some teams

### ISSUE THREAD

**Issue by stegreen1980** [lucacri/nycgha-stats#8]
I created new games for the Boxers but they do not appear when Boxers manager goes to update stats as the season does not exist.  There also seems to be no way to tie a game to a season in the UI.  I assume this will also be the case for the Wizards.
![image](https://cloud.githubusercontent.com/assets/11998123/7354322/c987921a-ece8-11e4-8f2b-9721513441fd.png)

**Comment by lucacri** [comment]
Solved, i forgot to add the field in the Admin -> Game where you can choose the season for the game
